# Generated by Django 5.0.14 on 2025-12-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0004_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(blank=True, to='auto_api.service', verbose_name='Услуги'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Итого'),
        ),
    ]
