# Generated by Django 5.0.14 on 2025-12-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_api', '0005_alter_order_created_at_alter_order_services_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
        migrations.AddField(
            model_name='car',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL картинки'),
        ),
    ]
